MSTR-338: 회원가입, 로그인 페이지 UI 디자인 적용
SW13-Monstera/frontend pull request #57
Opened 2022-10-28 08:33 UTC by Kim-Hyunjo

### Issue Number

close: MSTR-338, MSTR-339

### 작업 내역

> 구현 내용 및 작업 했던 내역
![스크린샷 2022-10-28 오후 5 29 27](https://user-images.githubusercontent.com/63906230/198542140-cf4b07d8-1857-48cd-878f-5b0fe3abe94c.png)

- [x] 회원가입, 로그인 페이지 UI 디자인 적용
- [x] 회원가입폼 값 validation
- [x] 개인정보약관, 이용약관 페이지 추가 (UI 디자인 추후 적용함)

### 작업 유형

- [x] 신규 기능 추가
- [ ] 버그 수정
- [ ] 리펙토링
- [ ] 문서 업데이트

### PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- validation 위주로 보시면 될듯합니다~!

2022-10-28 11:49 UTC, kshired requested changes

2022-10-28 11:49 UTC, kshired commented on src/Organism/LoginForm/index.tsx
> +          placeholder='example@csbroker.com'
csbroker.io 가 낫지 않을까요

2022-10-28 11:49 UTC, kshired commented on src/Page/JoinPage/index.tsx
> +              placeholder='example@csbroker.com'
csbroker.io

2022-10-28 11:49 UTC, kshired commented
위에 두 개 말고는 이견 없습니다 :)

2022-10-28 15:56 UTC, Kim-Hyunjo commented on src/Organism/LoginForm/index.tsx
> +          placeholder='example@csbroker.com'
논리적이고 멋진 제안이네요. 다만 최상위 도메인을 io로 바꾸면 일반사용자는 이메일이라는 사실이 직관적으로 느껴지지 않을 것 같은데 `example@email.com`이나 "이메일을 입력해주세요"로 바꾸는건 어떻게 생각하시나요?

2022-10-29 04:24 UTC, kshired commented
@Kim-Hyunjo "이메일을 입력해주세요"가 제일 좋은 것 같아요~!

2022-10-30 14:36 UTC, kshired approved these changes

2022-10-30 15:30 UTC, merged